import Link from 'next/link';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      {/* Hero Section */}
      <section className="py-20 bg-white dark:bg-gray-800">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 mb-10 md:mb-0">
              <h1 className="text-4xl md:text-5xl font-bold mb-6 text-gray-900 dark:text-white">
                Professional Headshots Generated by AI
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
                Transform your casual photos into studio-quality professional headshots in minutes. Perfect for LinkedIn, resumes, and corporate profiles.
              </p>
              <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
                <Link href="/create" className="bg-blue-600 hover:bg-blue-700 text-white py-3 px-6 rounded-md font-medium text-center">
                  Try It Free
                </Link>
                <Link href="/pricing" className="border border-gray-300 hover:border-gray-400 text-gray-700 dark:text-gray-200 py-3 px-6 rounded-md font-medium text-center dark:border-gray-600 dark:hover:border-gray-500">
                  View Pricing
                </Link>
              </div>
            </div>
            <div className="md:w-1/2 md:pl-10">
              {/* Placeholder for before/after headshot comparison */}
              <div className="bg-gray-200 rounded-lg w-full aspect-[4/3] flex items-center justify-center dark:bg-gray-700">
                <span className="text-gray-500 dark:text-gray-400">Headshot Comparison</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gray-50 dark:bg-gray-900">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
              Transform Your Photos Into Professional Headshots
            </h2>
            <p className="mt-4 text-xl text-gray-600 dark:text-gray-400">
              Our AI-powered platform makes it easy to create studio-quality portraits.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-10">
            {/* Feature 1 */}
            <div className="bg-white p-8 rounded-lg shadow-md dark:bg-gray-800">
              <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mb-6 dark:bg-blue-900">
                <svg className="w-6 h-6 text-blue-600 dark:text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"></path>
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                No Photoshoot Required
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Skip the professional photographer. Use any decent photo as a starting point and let our AI do the rest.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-white p-8 rounded-lg shadow-md dark:bg-gray-800">
              <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mb-6 dark:bg-green-900">
                <svg className="w-6 h-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                Customizable Styles
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Choose from multiple headshot styles including Corporate, Creative, Casual, Executive, and more.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-white p-8 rounded-lg shadow-md dark:bg-gray-800">
              <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mb-6 dark:bg-purple-900">
                <svg className="w-6 h-6 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                Ready in Minutes
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Generate multiple professional headshots in under 5 minutes. Download instantly or save to your account.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing CTA Section */}
      <section className="py-20 bg-white dark:bg-gray-800">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-6 text-gray-900 dark:text-white">
            Ready to Create Your Professional Headshot?
          </h2>
          <p className="text-xl mb-10 text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
            Start with 5 free generations. Upgrade anytime for additional headshots.
          </p>
          <Link href="/signup" className="bg-blue-600 hover:bg-blue-700 text-white py-3 px-8 rounded-md font-medium text-lg inline-block">
            Get Started Free
          </Link>
        </div>
      </section>
    </div>
  );
}