import Link from 'next/link';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      {/* Hero Section */}
      <section className="py-24 relative bg-white dark:bg-gray-900">
        {/* Decorative gradient blobs */}
        <div className="absolute -top-24 -left-24 w-96 h-96 bg-primary-200/30 dark:bg-primary-800/20 rounded-full filter blur-3xl opacity-70 pointer-events-none"></div>
        <div className="absolute -bottom-24 -right-24 w-96 h-96 bg-secondary-200/30 dark:bg-secondary-800/20 rounded-full filter blur-3xl opacity-70 pointer-events-none"></div>
        
        <div className="container mx-auto px-4 relative z-10">
          <div className="flex flex-col md:flex-row items-center">
            <div className="md:w-1/2 mb-12 md:mb-0">
              <div className="inline-block px-3 py-1 mb-6 text-xs font-medium text-primary-700 dark:text-primary-300 bg-primary-50 dark:bg-primary-900/30 rounded-full shadow-soft-sm">
                Powered by AI Technology
              </div>
              <h1 className="text-4xl md:text-6xl font-bold mb-6 leading-tight">
                <span className="text-transparent bg-clip-text bg-gradient-primary">Professional Headshots</span>
                <br />
                <span className="text-gray-900 dark:text-white">Generated by AI</span>
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300 mb-10 max-w-xl">
                Transform your casual photos into studio-quality professional headshots in minutes. Perfect for LinkedIn, resumes, and corporate profiles.
              </p>
              <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-5">
                <Link href="/create" className="ai-button-primary">
                  Try It Free
                </Link>
                <Link href="/pricing" className="ai-button-secondary">
                  View Pricing
                </Link>
              </div>
            </div>
            <div className="md:w-1/2 md:pl-10">
              {/* Placeholder for before/after headshot comparison */}
              <div className="relative">
                <div className="absolute inset-0 -m-4 bg-gradient-primary rounded-xl opacity-10 blur-2xl dark:opacity-20 pointer-events-none"></div>
                <div className="ai-card-highlight border-primary-200 dark:border-primary-800/40 relative w-full aspect-[4/3] flex items-center justify-center overflow-hidden rounded-xl shadow-soft-xl dark:shadow-glow-primary">
                  <span className="text-gray-500 dark:text-gray-400">Headshot Comparison</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-gray-50 dark:bg-gray-800 relative">
        {/* Decorative pattern */}
        <div className="absolute inset-0 ai-grid-pattern opacity-50 pointer-events-none"></div>
        
        <div className="container mx-auto px-4 relative z-10">
          <div className="text-center mb-20">
            <div className="inline-block px-3 py-1 mb-4 text-xs font-medium text-primary-700 dark:text-primary-300 bg-primary-50 dark:bg-primary-900/30 rounded-full shadow-soft-sm">
              Key Benefits
            </div>
            <h2 className="text-3xl md:text-5xl font-bold mb-6 text-gray-900 dark:text-white">
              Transform Your Photos Into <span className="text-transparent bg-clip-text bg-gradient-primary">Professional Headshots</span>
            </h2>
            <p className="mt-4 text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
              Our AI-powered platform makes it easy to create studio-quality portraits with advanced technology.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-10">
            {/* Feature 1 */}
            <div className="ai-card group hover:shadow-soft-lg transition-all duration-300 hover:-translate-y-1">
              <div className="w-14 h-14 bg-gradient-to-br from-primary-500 to-primary-600 rounded-full flex items-center justify-center mb-6 shadow-soft-md group-hover:shadow-glow-primary transition-all duration-300">
                <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"></path>
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                No Photoshoot Required
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Skip the professional photographer. Use any decent photo as a starting point and let our AI transform it into a studio-quality image.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="ai-card group hover:shadow-soft-lg transition-all duration-300 hover:-translate-y-1">
              <div className="w-14 h-14 bg-gradient-to-br from-secondary-500 to-secondary-600 rounded-full flex items-center justify-center mb-6 shadow-soft-md group-hover:shadow-glow-secondary transition-all duration-300">
                <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                Customizable Styles
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Choose from multiple headshot styles including Corporate, Creative, Casual, Executive, and more to match your personal brand and needs.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="ai-card group hover:shadow-soft-lg transition-all duration-300 hover:-translate-y-1">
              <div className="w-14 h-14 bg-gradient-to-br from-accent-500 to-accent-600 rounded-full flex items-center justify-center mb-6 shadow-soft-md group-hover:shadow-glow-accent transition-all duration-300">
                <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-4 text-gray-900 dark:text-white">
                Ready in Minutes
              </h3>
              <p className="text-gray-600 dark:text-gray-400">
                Generate multiple professional headshots in under 5 minutes. Download instantly or save to your account for future use.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Process Section */}
      <section className="py-24 bg-white dark:bg-gray-900">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <div className="inline-block px-3 py-1 mb-4 text-xs font-medium text-secondary-700 dark:text-secondary-300 bg-secondary-50 dark:bg-secondary-900/30 rounded-full shadow-soft-sm">
              How It Works
            </div>
            <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900 dark:text-white">
              Create Your Perfect <span className="text-transparent bg-clip-text bg-gradient-secondary">Professional Headshot</span> in 3 Easy Steps
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-10 max-w-5xl mx-auto">
            {/* Step 1 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mb-6 border-4 border-white dark:border-gray-900 shadow-soft-lg relative z-10">
                <span className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-primary">1</span>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-gray-900 dark:text-white">Upload Your Photo</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Start with any decent selfie or casual photo as your base image.
              </p>
            </div>

            {/* Connecting line */}
            <div className="hidden md:block absolute left-1/3 right-1/3 top-1/2 h-0.5 bg-gradient-to-r from-primary-200 to-secondary-200 dark:from-primary-800 dark:to-secondary-800 -z-10"></div>

            {/* Step 2 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mb-6 border-4 border-white dark:border-gray-900 shadow-soft-lg relative z-10">
                <span className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-secondary">2</span>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-gray-900 dark:text-white">Customize Your Style</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Select from our range of professional styles and customize to your preferences.
              </p>
            </div>

            {/* Step 3 */}
            <div className="flex flex-col items-center text-center">
              <div className="w-16 h-16 rounded-full bg-gray-100 dark:bg-gray-800 flex items-center justify-center mb-6 border-4 border-white dark:border-gray-900 shadow-soft-lg relative z-10">
                <span className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-accent">3</span>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-gray-900 dark:text-white">Generate & Download</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Our AI generates multiple variations for you to choose from and download.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing CTA Section */}
      <section className="py-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-gray-50 to-white dark:from-gray-800 dark:to-gray-900"></div>
        
        {/* Decorative circle patterns */}
        <div className="absolute top-0 left-0 w-full h-full pointer-events-none">
          <div className="absolute top-10 left-10 w-64 h-64 rounded-full border border-primary-200 dark:border-primary-800/30 opacity-50"></div>
          <div className="absolute bottom-10 right-10 w-96 h-96 rounded-full border border-secondary-200 dark:border-secondary-800/30 opacity-50"></div>
        </div>
        
        <div className="container mx-auto px-4 text-center relative z-10">
          <div className="max-w-3xl mx-auto bg-white dark:bg-gray-800 rounded-2xl shadow-soft-xl p-10 dark:shadow-glow-primary">
            <div className="inline-block px-3 py-1 mb-4 text-xs font-medium text-accent-700 dark:text-accent-300 bg-accent-50 dark:bg-accent-900/30 rounded-full shadow-soft-sm">
              Limited Time Offer
            </div>
            <h2 className="text-3xl md:text-4xl font-bold mb-6 text-gray-900 dark:text-white">
              Ready to Create Your <span className="text-transparent bg-clip-text bg-gradient-accent">Professional Headshot</span>?
            </h2>
            <p className="text-xl mb-10 text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
              Start with 5 free generations. Upgrade anytime for additional headshots and premium features.
            </p>
            <div className="flex flex-col sm:flex-row justify-center space-y-4 sm:space-y-0 sm:space-x-5">
              <Link href="/signup" className="ai-button-primary text-lg px-8 py-4">
                Get Started Free
              </Link>
              <Link href="/pricing" className="ai-button-secondary text-lg px-8 py-4">
                View Pricing Plans
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
